version: '3.9'

services:

  imaphub-smtp:
    restart: "unless-stopped"
    container_name: imaphub-smtp
    image: mailhog/mailhog:latest
    logging:
      driver: 'none'  # disable saving logs
    ports:
    - "1125:1025" # smtp server
    - "8125:8025" # web ui

  imaphub-imap:
    restart: "unless-stopped"
    container_name: imaphub-imap
    image: dovecot/dovecot
    ports:
    - "1143:143"
    depends_on:
    - imaphub-smtp

  imaphub-api:
    restart: "unless-stopped"
    container_name: imaphub-api
    build:
      context: .
    ports:
    - "4001:4001"
    depends_on:
    - imaphub-smtp
    - imaphub-imap
    environment:
    - IMAP_SERVER=imaphub-imap
    - IMAP_PORT=1143
    - IMAP_USERNAME=alice
    - IMAP_PASSWORD=pass
    - IMAP_MAILBOX=default
    - HOST=0.0.0.0
    - PORT=4001
