FROM python:3.9-slim-buster

ARG IMAP_SERVER
ARG IMAP_USERNAME
ARG IMAP_PASSWORD
ARG IMAP_MAILBOX
ARG HOST
ARG PORT

ENV IMAP_SERVER=${IMAP_SERVER}
ENV IMAP_USERNAME=${IMAP_USERNAME}
ENV IMAP_PASSWORD=${IMAP_PASSWORD}
ENV IMAP_MAILBOX=${IMAP_MAILBOX}
ENV HOST=${HOST}
ENV PORT=${PORT}

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "app.py"]
