FROM python:3.9-slim-buster

ARG IMAP_SSL=false
ARG IMAP_SERVER=default-server
ARG IMAP_PORT=143
ARG IMAP_USERNAME=default-username
ARG IMAP_PASSWORD=default-password
ARG IMAP_MAILBOX=default-mailbox
ARG HOST=0.0.0.0
ARG PORT=4001

ENV IMAP_SSL=${IMAP_SSL}
ENV IMAP_SERVER=${IMAP_SERVER}
ENV IMAP_PORT=${IMAP_PORT}
ENV IMAP_USERNAME=${IMAP_USERNAME}
ENV IMAP_PASSWORD=${IMAP_PASSWORD}
ENV IMAP_MAILBOX=${IMAP_MAILBOX}
ENV HOST=${HOST}
ENV PORT=${PORT}

WORKDIR /app

COPY requirements.txt /src/requirements.txt

RUN pip install --no-cache-dir -r /src/requirements.txt

VOLUME /app
CMD [ "flask", "--app", "app.py", "--debug", "run", "--reload", "--host=0.0.0.0", "--port=4001" ]
