version: '3'

services:
  imaphub-systemtest:
    restart: "unless-stopped"
    container_name: imaphub-systemtest
    build:
      context: .
      dockerfile: Dockerfile.systemtest
    environment:
      API_URL: "http://host.docker.internal:4001"
